CREATE TABLE IF NOT EXISTS "order" (
    id SERIAL PRIMARY KEY  NOT NULL,
    user_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    quantity INTEGER DEFAULT 1,
    "status" VARCHAR(50) NOT NULL,

    FOREIGN KEY (product_id) REFERENCES "product"(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE ON UPDATE CASCADE
);