CREATE TABLE IF NOT EXISTS "order" (
    id SERIAL PRIMARY KEY  NOT NULL,
    user_id INTEGER NOT NULL,
    "status" VARCHAR(50) NOT NULL,

    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE ON UPDATE CASCADE
);